# Generated by Django 2.1 on 2018-11-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hint', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'en')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.Key')),
            ],
        ),
    ]
