# Generated by Django 2.1 on 2018-11-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
