# Generated by Django 2.1 on 2018-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20181117_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('sv', 'sv')], max_length=10),
        ),
    ]
