# Generated by Django 2.1 on 2018-12-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20181120_1918'),
        ('translation', '0003_auto_20181123_1006'),
    ]

    operations = [
    ]
